name: unihome
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.0.17
  platform_device_id: ^1.0.1
  jiffy: ^4.1.0
  dropdown_button2: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2
  expandable: ^5.0.1
  buttons_tabbar: ^1.3.6
  image_picker: ^0.8.7
  intl: ^0.17.0
  flutter_format_money_vietnam: ^0.0.2
  cached_network_image: ^3.2.3
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.11

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logos/logo-2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 900
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
